export type Severity = 'Critical' | 'High' | 'Medium' | 'Low' | 'Informational'
export type AlertStatus = 'New' | 'Enriching' | 'Responding' | 'Resolved'
export type CaseStatus = 'Open' | 'Investigating' | 'Contained' | 'Closed'
export type SimStatus = 'Planned' | 'Scripted' | 'Tested' | 'Detected'
export type ApprovalStatus = 'None' | 'Pending' | 'Approved' | 'Rejected'
export type SourceStatus = 'hit' | 'clean' | 'pending' | 'skipped'
export type UserRole = 'l1_analyst' | 'l2_analyst' | 'admin'
export type UserStatus = 'pending' | 'approved' | 'rejected'

/** A `profiles` row, as the admin panel and Settings page see it. */
export interface AdminUser {
  id: string
  email: string
  displayName: string
  firstName: string
  lastName: string
  avatarUrl: string
  role: UserRole
  status: UserStatus
  themePreference: 'dark' | 'light'
  createdAt: string
}

/** Where a piece of enrichment came from — mirrors the real SOCore pipeline. */
export interface EnrichmentSource {
  name: 'Wazuh' | 'MISP' | 'Cortex' | 'VirusTotal' | 'AbuseIPDB' | 'TheHive'
  status: SourceStatus
  detail: string
  at: string
}

/** A response action the automation proposes but will not run without a human. */
export interface ProposedAction {
  action: string
  target: string
  playbook: string
  dryRun: boolean
}

export interface Alert {
  id: string
  timestamp: string
  severity: Severity
  sourceIP: string
  attackType: string
  mitreId: string
  mitreName: string
  status: AlertStatus
  analyst: string
  raw: string
  vtScore: number
  abuseScore: number
  country: string
  asn: string
  detectedAt: string
  enrichedAt: string
  respondedAt: string
  /** 0–100 score produced by the correlation engine. Drives playbook thresholds. */
  riskScore: number
  /** Plain-language reasoning generated by the AI layer. */
  aiExplanation: string
  aiConfidence: number
  /** Populated when risk_score crosses the playbook threshold. */
  proposedAction: ProposedAction | null
  approvalStatus: ApprovalStatus
  sources: EnrichmentSource[]
  /** The raw Wazuh event this alert was scored from, if any (seed alerts have none). */
  sourceEventId?: string | null
}

/** A raw, unscored Wazuh event — recorded independently of whatever Alert it becomes. */
export interface WazuhRawEvent {
  id: string
  timestamp: string
  sourceIP: string
  ruleId: string
  ruleLevel: number
  ruleDescription: string
  raw: string
  agentId: string
  agentName: string
  /** Set once the correlation engine turns this event into an Alert. Not every event is. */
  alertId: string | null
}

/** Alert fields authored by hand; the rest are derived below. */
type AlertSeed = Omit<Alert, 'riskScore' | 'aiExplanation' | 'aiConfidence' | 'proposedAction' | 'approvalStatus' | 'sources'>

export interface CaseTask {
  id: string
  title: string
  done: boolean
}

export interface CaseNote {
  author: string
  text: string
  at: string
}

export interface Case {
  id: string
  title: string
  severity: Severity
  status: CaseStatus
  assignedTo: string
  created: string
  alertCount: number
  tags: string[]
  /** Present when the case came from the live backend. */
  alertIds?: string[]
  riskScore?: number
  summary?: string
  tasks?: CaseTask[]
  notes?: CaseNote[]
}

export interface Simulation {
  id: string
  name: string
  mitreId: string
  killChain: string
  status: SimStatus
  lastRun: string
  ttd: string
}

const baseAlerts: AlertSeed[] = [
  {
    id: 'ALT-20240118-001',
    timestamp: '2024-01-18 09:42:17',
    severity: 'Critical',
    sourceIP: '192.168.56.20',
    attackType: 'Brute Force',
    mitreId: 'T1110',
    mitreName: 'Brute Force',
    status: 'New',
    analyst: 'Unassigned',
    raw: `Jan 18 09:42:17 auth sshd[14832]: Failed password for root from 192.168.56.20 port 54231 ssh2
Jan 18 09:42:18 auth sshd[14833]: Failed password for admin from 192.168.56.20 port 54232 ssh2
Jan 18 09:42:19 auth sshd[14834]: Failed password for ubuntu from 192.168.56.20 port 54233 ssh2
Jan 18 09:42:19 auth sshd[14835]: Failed password for root from 192.168.56.20 port 54234 ssh2
Jan 18 09:42:20 auth sshd[14836]: Failed password for root from 192.168.56.20 port 54235 ssh2
# 847 more failed attempts in 00:04:22 window`,
    vtScore: 85,
    abuseScore: 92,
    country: 'RU',
    asn: 'AS15169 Google LLC',
    detectedAt: '09:42:17',
    enrichedAt: '09:42:31',
    respondedAt: '09:43:05',
  },
  {
    id: 'ALT-20240118-002',
    timestamp: '2024-01-18 09:38:04',
    severity: 'High',
    sourceIP: '10.0.0.47',
    attackType: 'Lateral Movement',
    mitreId: 'T1021',
    mitreName: 'Remote Services',
    status: 'Enriching',
    analyst: 'K. Osei',
    raw: `Jan 18 09:38:04 kernel: [UFW BLOCK] SRC=10.0.0.47 DST=10.0.0.12 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=12456 DF PROTO=TCP SPT=51234 DPT=445 WINDOW=64240 RES=0x00 SYN URGP=0
Jan 18 09:38:04 kernel: [UFW BLOCK] SRC=10.0.0.47 DST=10.0.0.13 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=12457 DF PROTO=TCP SPT=51234 DPT=445 WINDOW=64240 RES=0x00 SYN URGP=0`,
    vtScore: 12,
    abuseScore: 0,
    country: 'INTERNAL',
    asn: 'CORP-NET',
    detectedAt: '09:38:04',
    enrichedAt: '09:38:18',
    respondedAt: '',
  },
  {
    id: 'ALT-20240118-003',
    timestamp: '2024-01-18 09:31:55',
    severity: 'High',
    sourceIP: '203.0.113.42',
    attackType: 'Phishing',
    mitreId: 'T1566',
    mitreName: 'Phishing',
    status: 'Responding',
    analyst: 'M. Tanaka',
    raw: `Received: from mail.phish-domain.ru (203.0.113.42)
Subject: ACTION REQUIRED: Your account has been compromised
From: "IT Security Team" <security@phish-domain.ru>
X-Spam-Score: 8.4
X-Spam-Status: Yes, score=8.4 required=5.0
Content includes: malicious URL https://bit.ly/3xFakeLink`,
    vtScore: 97,
    abuseScore: 88,
    country: 'CN',
    asn: 'AS4134 CHINANET',
    detectedAt: '09:31:55',
    enrichedAt: '09:32:10',
    respondedAt: '09:34:22',
  },
  {
    id: 'ALT-20240118-004',
    timestamp: '2024-01-18 09:25:11',
    severity: 'Medium',
    sourceIP: '172.16.0.88',
    attackType: 'Port Scan',
    mitreId: 'T1046',
    mitreName: 'Network Service Discovery',
    status: 'Resolved',
    analyst: 'A. Petrov',
    raw: `Jan 18 09:25:11 snort[1234]: [1:2010936:3] ET SCAN Nmap Scripting Engine User-Agent Detected [Classification: Web Application Attack] [Priority: 1] {TCP} 172.16.0.88:52341 -> 10.0.0.1:80`,
    vtScore: 5,
    abuseScore: 3,
    country: 'INTERNAL',
    asn: 'CORP-DMZ',
    detectedAt: '09:25:11',
    enrichedAt: '09:25:24',
    respondedAt: '09:26:00',
  },
  {
    id: 'ALT-20240118-005',
    timestamp: '2024-01-18 09:18:33',
    severity: 'Critical',
    sourceIP: '198.51.100.7',
    attackType: 'C2 Beacon',
    mitreId: 'T1071',
    mitreName: 'App Layer Protocol',
    status: 'Responding',
    analyst: 'K. Osei',
    raw: `Jan 18 09:18:33 fw01 CEF:0|PaloAlto|NGFW|10.1|THREAT|threat|5|src=198.51.100.7 dst=10.0.0.99 dpt=443 cs1=beacon cs1Label=ThreatType msg=C2 beacon detected interval=60s bytes=842`,
    vtScore: 76,
    abuseScore: 81,
    country: 'IR',
    asn: 'AS197207 Mobile Communication',
    detectedAt: '09:18:33',
    enrichedAt: '09:18:47',
    respondedAt: '09:20:15',
  },
  {
    id: 'ALT-20240118-006',
    timestamp: '2024-01-18 09:11:08',
    severity: 'Low',
    sourceIP: '10.0.0.22',
    attackType: 'Persistence',
    mitreId: 'T1547',
    mitreName: 'Boot/Logon Autostart',
    status: 'New',
    analyst: 'Unassigned',
    raw: `Jan 18 09:11:08 auditd[1247]: type=SYSCALL msg=audit(1705571468.123:4592): arch=c000003e syscall=257 success=yes exit=3 a0=ffffff9c a1=7ffd12345678 a2=241 a3=1b6 items=2 ppid=2341 pid=2342 auid=1000 uid=0 gid=0 euid=0 egid=0 suid=0 sgid=0 fsuid=0 fsgid=0 tty=pts0 ses=14 comm="bash" exe="/bin/bash" key="startup_files"`,
    vtScore: 0,
    abuseScore: 0,
    country: 'INTERNAL',
    asn: 'CORP-NET',
    detectedAt: '09:11:08',
    enrichedAt: '',
    respondedAt: '',
  },
]

// ── Additional queue alerts (triage backlog) ────────────────────────────────
const queueSeed: Array<[string, string, Severity, string, string, string, string, AlertStatus, string, number, number, string, string]> = [
  ['007', '09:05:41', 'High', '45.155.205.233', 'Brute Force', 'T1110', 'Brute Force', 'New', 'Unassigned', 71, 78, 'NL', 'AS204428 SS-Net'],
  ['008', '08:58:12', 'Medium', '10.0.0.14', 'Port Scan', 'T1046', 'Network Service Discovery', 'Enriching', 'A. Petrov', 2, 0, 'INTERNAL', 'CORP-NET'],
  ['009', '08:51:37', 'Critical', '185.220.101.44', 'C2 Beacon', 'T1071', 'App Layer Protocol', 'New', 'Unassigned', 94, 96, 'DE', 'AS205100 F3 Netze'],
  ['010', '08:47:02', 'Low', '10.0.0.61', 'Persistence', 'T1547', 'Boot/Logon Autostart', 'Resolved', 'A. Petrov', 0, 0, 'INTERNAL', 'CORP-NET'],
  ['011', '08:39:55', 'High', '91.208.184.12', 'Credential Dumping', 'T1003', 'OS Credential Dumping', 'Responding', 'K. Osei', 68, 74, 'BG', 'AS49392 Telepoint'],
  ['012', '08:33:19', 'Medium', '172.16.0.101', 'Lateral Movement', 'T1021', 'Remote Services', 'Enriching', 'M. Tanaka', 8, 4, 'INTERNAL', 'CORP-DMZ'],
  ['013', '08:26:44', 'Critical', '104.244.72.115', 'Malware Execution', 'T1204', 'User Execution', 'Responding', 'K. Osei', 99, 91, 'US', 'AS53667 FranTech'],
  ['014', '08:19:08', 'Informational', '10.0.0.5', 'Policy Violation', 'T1078', 'Valid Accounts', 'Resolved', 'A. Petrov', 0, 0, 'INTERNAL', 'CORP-NET'],
  ['015', '08:12:31', 'High', '212.102.35.9', 'Phishing', 'T1566', 'Phishing', 'New', 'Unassigned', 83, 69, 'GB', 'AS9009 M247'],
  ['016', '08:04:57', 'Medium', '10.0.0.33', 'Defense Evasion', 'T1070', 'Indicator Removal', 'Enriching', 'M. Tanaka', 3, 0, 'INTERNAL', 'CORP-NET'],
  ['017', '07:58:22', 'Low', '172.16.0.44', 'Port Scan', 'T1046', 'Network Service Discovery', 'Resolved', 'A. Petrov', 1, 0, 'INTERNAL', 'CORP-DMZ'],
  ['018', '07:49:46', 'Critical', '77.83.36.190', 'Brute Force', 'T1110', 'Brute Force', 'Responding', 'K. Osei', 88, 95, 'RU', 'AS208046 Hostslick'],
  ['019', '07:41:03', 'High', '10.0.0.77', 'Priv. Escalation', 'T1548', 'Abuse Elevation Control', 'New', 'Unassigned', 0, 0, 'INTERNAL', 'CORP-NET'],
  ['020', '07:33:28', 'Medium', '198.98.51.189', 'Exfiltration', 'T1048', 'Exfil Alt Protocol', 'Enriching', 'M. Tanaka', 47, 52, 'US', 'AS53667 FranTech'],
  ['021', '07:25:11', 'Low', '10.0.0.19', 'Discovery', 'T1087', 'Account Discovery', 'Resolved', 'A. Petrov', 0, 0, 'INTERNAL', 'CORP-NET'],
  ['022', '07:17:39', 'High', '5.188.206.34', 'Web Exploit', 'T1190', 'Exploit Public App', 'New', 'Unassigned', 79, 84, 'RU', 'AS49505 Selectel'],
  ['023', '07:09:04', 'Informational', '10.0.0.8', 'Audit Event', 'T1078', 'Valid Accounts', 'Resolved', 'System', 0, 0, 'INTERNAL', 'CORP-NET'],
  ['024', '07:01:52', 'Critical', '162.247.74.201', 'Ransomware Precursor', 'T1486', 'Data Encrypted for Impact', 'Responding', 'K. Osei', 96, 89, 'CA', 'AS4224 Calyx'],
]

const queueAlerts: AlertSeed[] = queueSeed.map(([n, time, severity, ip, attack, mid, mname, status, analyst, vt, abuse, country, asn]) => ({
  id: `ALT-20240118-${n}`,
  timestamp: `2024-01-18 ${time}`,
  severity,
  sourceIP: ip,
  attackType: attack,
  mitreId: mid,
  mitreName: mname,
  status,
  analyst,
  raw: `Jan 18 ${time} sensor: ${attack} signature matched for ${ip} (${mid})\n# Full event payload available in the SIEM index`,
  vtScore: vt,
  abuseScore: abuse,
  country,
  asn,
  detectedAt: time,
  enrichedAt: status === 'New' ? '' : time,
  respondedAt: status === 'Responding' || status === 'Resolved' ? time : '',
}))



// ── Correlation + AI layer ──────────────────────────────────────────────────
// In production these fields arrive from the backend: the correlation engine
// computes risk_score, the AI layer writes ai_explanation, and the SOAR
// playbook attaches a proposed action once the score crosses its threshold.

const severityWeight: Record<Severity, number> = {
  Critical: 46, High: 33, Medium: 20, Low: 10, Informational: 4,
}

/** Same weighting the backend correlation engine applies. */
function computeRisk(a: AlertSeed): number {
  const reputation = Math.max(a.vtScore, a.abuseScore) * 0.42
  const external = a.country === 'INTERNAL' ? 0 : 8
  const unresolved = a.status === 'Resolved' ? -14 : 0
  return Math.max(0, Math.min(100, Math.round(severityWeight[a.severity] + reputation + external + unresolved)))
}

const actionByAttack: Record<string, string> = {
  'Brute Force': 'Block source IP at the perimeter firewall',
  'C2 Beacon': 'Block outbound destination and isolate the host',
  'Phishing': 'Quarantine the message and reset the recipient session',
  'Malware Execution': 'Isolate the endpoint and kill the parent process',
  'Ransomware Precursor': 'Isolate the endpoint and revoke the account session',
  'Credential Dumping': 'Force password reset and revoke active tokens',
  'Web Exploit': 'Block source IP and apply the WAF rule',
  'Lateral Movement': 'Block SMB between the two hosts',
  'Exfiltration': 'Block the destination and throttle the egress path',
}

const handwrittenExplanations: Record<string, string> = {
  'ALT-20240118-001':
    'Roughly 850 failed SSH logins arrived from a single address inside four minutes, cycling through root, admin and ubuntu. That pattern is credential stuffing, not a user mistyping a password. The address is already listed on two reputation feeds, so this is very likely an automated attack rather than a misconfigured internal service.',
  'ALT-20240118-002':
    'An internal host tried to reach SMB on several neighbours in quick succession and the firewall dropped each attempt. Reputation feeds show nothing, which is expected for an internal address, so the signal here is the behaviour: one machine probing many peers on a file-sharing port usually means an attacker moving sideways after an initial foothold.',
  'ALT-20240118-003':
    'The message claims to come from the internal IT team but was sent from an external domain and carries a shortened link. The sending address scores near the top of both reputation feeds. The combination of a spoofed sender, urgency in the subject line and a masked URL is the standard shape of credential harvesting.',
  'ALT-20240118-005':
    'A workstation is contacting the same external address every sixty seconds with near-identical payload sizes. Human traffic is irregular; this regularity is what a command-and-control beacon looks like. The destination appears on a botnet tracker feed, which supports the beacon reading.',
  'ALT-20240118-009':
    'Same beaconing pattern as the earlier C2 detection but against a different endpoint, and the destination scores higher on both feeds. Two hosts talking to related infrastructure suggests the intrusion is no longer contained to one machine.',
  'ALT-20240118-013':
    'A user opened an attachment that spawned a scripting process, which then wrote to a startup location. Execution followed by persistence in one chain is the behaviour of a malware dropper, and the origin address is flagged by nearly every reputation source.',
  'ALT-20240118-024':
    'Shadow copies were deleted and a large number of files were opened for write in rapid succession. Those two things together are what ransomware does immediately before encryption begins. This should be treated as time-critical.',
}

function explain(a: AlertSeed, risk: number): string {
  const known = handwrittenExplanations[a.id]
  if (known) return known
  const rep = Math.max(a.vtScore, a.abuseScore)
  const origin = a.country === 'INTERNAL'
    ? 'The source is an internal address, so reputation feeds add nothing and the behaviour itself carries the signal.'
    : rep >= 70
      ? `The source address is flagged by threat intelligence with a confidence of ${rep}, which raises the weight of this detection considerably.`
      : rep > 0
        ? `Threat intelligence returns a low confidence of ${rep} for this address, so the detection rests mainly on the observed behaviour.`
        : 'Threat intelligence has no record of this address, so the detection rests entirely on the observed behaviour.'
  return `Activity matching ${a.mitreName} (${a.mitreId}) was observed from ${a.sourceIP}. ${origin} The correlation engine scored this at ${risk}, which places it ${risk > 70 ? 'above' : 'below'} the automatic response threshold.`
}

function buildSources(a: AlertSeed): EnrichmentSource[] {
  const rep = Math.max(a.vtScore, a.abuseScore)
  const internal = a.country === 'INTERNAL'
  const enriched = !!a.enrichedAt
  return [
    { name: 'Wazuh', status: 'hit', detail: `Rule matched on ${a.mitreId}`, at: a.detectedAt },
    {
      name: 'MISP',
      status: internal ? 'skipped' : rep >= 70 ? 'hit' : enriched ? 'clean' : 'pending',
      detail: internal
        ? 'Internal address — not submitted to the IOC database'
        : rep >= 70
          ? 'Address appears in an active IOC event'
          : enriched ? 'No matching IOC event' : 'Lookup queued',
      at: a.enrichedAt || '—',
    },
    {
      name: 'Cortex',
      status: enriched ? 'hit' : 'pending',
      detail: enriched ? 'Analyzers completed' : 'Analyzers not yet run',
      at: a.enrichedAt || '—',
    },
    {
      name: 'VirusTotal',
      status: enriched ? (a.vtScore >= 40 ? 'hit' : 'clean') : 'pending',
      detail: enriched ? `Malicious score ${a.vtScore}/100` : 'Awaiting analyzer run',
      at: a.enrichedAt || '—',
    },
    {
      name: 'AbuseIPDB',
      status: enriched ? (a.abuseScore >= 40 ? 'hit' : 'clean') : 'pending',
      detail: enriched ? `Abuse confidence ${a.abuseScore}%` : 'Awaiting analyzer run',
      at: a.enrichedAt || '—',
    },
    {
      name: 'TheHive',
      status: a.status === 'Responding' || a.status === 'Resolved' ? 'hit' : 'skipped',
      detail: a.status === 'Responding' || a.status === 'Resolved'
        ? 'Case opened from this alert'
        : 'No case opened yet',
      at: a.respondedAt || '—',
    },
  ]
}

/** Alerts already carrying a human decision, so the demo shows all four states. */
const decided: Record<string, ApprovalStatus> = {
  'ALT-20240118-003': 'Approved',
  'ALT-20240118-005': 'Approved',
  'ALT-20240118-011': 'Approved',
  'ALT-20240118-004': 'Rejected',
  'ALT-20240118-018': 'Approved',
}

export const alerts: Alert[] = [...baseAlerts, ...queueAlerts].map(a => {
  const riskScore = computeRisk(a)
  // The playbook threshold: only alerts above 70 get a proposed response action.
  const needsAction = riskScore > 70 && a.status !== 'Resolved'
  const proposedAction: ProposedAction | null = needsAction
    ? {
        action: actionByAttack[a.attackType] ?? 'Block source IP at the perimeter firewall',
        target: a.sourceIP,
        playbook: `PB-${a.attackType.toLowerCase().replace(/[^a-z]+/g, '-')}`,
        dryRun: true,
      }
    : null
  return {
    ...a,
    riskScore,
    aiExplanation: explain(a, riskScore),
    aiConfidence: Math.min(99, 60 + Math.round(Math.max(a.vtScore, a.abuseScore) * 0.3)),
    proposedAction,
    approvalStatus: proposedAction ? (decided[a.id] ?? 'Pending') : 'None',
    sources: buildSources(a),
  }
})

export const cases: Case[] = [
  {
    id: 'CASE-2024-0042',
    title: 'Coordinated SSH Brute Force Campaign',
    severity: 'Critical',
    status: 'Investigating',
    assignedTo: 'K. Osei',
    created: '2024-01-18 09:45',
    alertCount: 14,
    tags: ['brute-force', 'ssh', 'external'],
  },
  {
    id: 'CASE-2024-0041',
    title: 'Suspected C2 Callback — WKSTN-088',
    severity: 'Critical',
    status: 'Investigating',
    assignedTo: 'M. Tanaka',
    created: '2024-01-18 09:22',
    alertCount: 3,
    tags: ['c2', 'beacon', 'malware'],
  },
  {
    id: 'CASE-2024-0040',
    title: 'Phishing Email — Credential Harvesting',
    severity: 'High',
    status: 'Investigating',
    assignedTo: 'M. Tanaka',
    created: '2024-01-18 09:35',
    alertCount: 7,
    tags: ['phishing', 'email', 'credential'],
  },
  {
    id: 'CASE-2024-0039',
    title: 'Internal Port Sweep — DMZ Segment',
    severity: 'Medium',
    status: 'Closed',
    assignedTo: 'A. Petrov',
    created: '2024-01-17 16:30',
    alertCount: 2,
    tags: ['scan', 'internal', 'dmz'],
  },
  {
    id: 'CASE-2024-0038',
    title: 'Anomalous Admin Account Activity',
    severity: 'High',
    status: 'Open',
    assignedTo: 'Unassigned',
    created: '2024-01-18 08:10',
    alertCount: 5,
    tags: ['insider', 'privilege', 'admin'],
  },
  {
    id: 'CASE-2024-0037',
    title: 'Lateral Movement via SMB',
    severity: 'High',
    status: 'Open',
    assignedTo: 'Unassigned',
    created: '2024-01-18 09:40',
    alertCount: 8,
    tags: ['lateral', 'smb', 'internal'],
  },
]

export const simulations: Simulation[] = [
  { id: 'SIM-001', name: 'SSH Brute Force (Hydra)', mitreId: 'T1110.001', killChain: 'Credential Access', status: 'Detected', lastRun: '2024-01-17 14:30', ttd: '00:02:14' },
  { id: 'SIM-002', name: 'Cobalt Strike Beacon', mitreId: 'T1071.001', killChain: 'Command & Control', status: 'Detected', lastRun: '2024-01-16 11:00', ttd: '00:08:45' },
  { id: 'SIM-003', name: 'LSASS Memory Dump', mitreId: 'T1003.001', killChain: 'Credential Access', status: 'Tested', lastRun: '2024-01-15 09:15', ttd: '00:15:32' },
  { id: 'SIM-004', name: 'Scheduled Task Persistence', mitreId: 'T1053.005', killChain: 'Persistence', status: 'Scripted', lastRun: '2024-01-14 16:00', ttd: '—' },
  { id: 'SIM-005', name: 'Kerberoasting', mitreId: 'T1558.003', killChain: 'Credential Access', status: 'Planned', lastRun: 'Never', ttd: '—' },
  { id: 'SIM-006', name: 'PowerShell Encoded Command', mitreId: 'T1059.001', killChain: 'Execution', status: 'Detected', lastRun: '2024-01-17 10:45', ttd: '00:01:08' },
  { id: 'SIM-007', name: 'WMI Lateral Movement', mitreId: 'T1021.006', killChain: 'Lateral Movement', status: 'Tested', lastRun: '2024-01-13 13:20', ttd: '00:22:17' },
  { id: 'SIM-008', name: 'DNS Tunneling Exfil', mitreId: 'T1048.003', killChain: 'Exfiltration', status: 'Scripted', lastRun: '2024-01-12 15:00', ttd: '—' },
  { id: 'SIM-009', name: 'NTLM Relay Attack', mitreId: 'T1557.001', killChain: 'Credential Access', status: 'Planned', lastRun: 'Never', ttd: '—' },
  { id: 'SIM-010', name: 'Registry Run Key Persistence', mitreId: 'T1547.001', killChain: 'Persistence', status: 'Detected', lastRun: '2024-01-17 08:30', ttd: '00:03:55' },
]

export const riskTrendData = [
  { time: '00:00', score: 42 }, { time: '01:00', score: 38 }, { time: '02:00', score: 35 },
  { time: '03:00', score: 41 }, { time: '04:00', score: 44 }, { time: '05:00', score: 39 },
  { time: '06:00', score: 52 }, { time: '07:00', score: 61 }, { time: '08:00', score: 58 },
  { time: '09:00', score: 74 }, { time: '09:42', score: 81 }, { time: '10:00', score: 79 },
]

export const attackTypeData = [
  { name: 'Brute Force', count: 47 },
  { name: 'Port Scan', count: 31 },
  { name: 'Phishing', count: 24 },
  { name: 'Lateral Movement', count: 18 },
  { name: 'Persistence', count: 12 },
  { name: 'C2 Beacon', count: 9 },
]

export const mitreMatrix = [
  {
    tactic: 'Reconnaissance',
    id: 'TA0043',
    techniques: [
      { id: 'T1595', name: 'Active Scanning', status: 'detected' },
      { id: 'T1590', name: 'Gather Host Info', status: 'partial' },
      { id: 'T1591', name: 'Gather Org Info', status: 'none' },
      { id: 'T1598', name: 'Phishing for Info', status: 'partial' },
      { id: 'T1597', name: 'Search Closed Sources', status: 'none' },
    ],
  },
  {
    tactic: 'Initial Access',
    id: 'TA0001',
    techniques: [
      { id: 'T1566', name: 'Phishing', status: 'detected' },
      { id: 'T1190', name: 'Exploit Public App', status: 'detected' },
      { id: 'T1133', name: 'External Remote Svc', status: 'partial' },
      { id: 'T1078', name: 'Valid Accounts', status: 'partial' },
      { id: 'T1091', name: 'Removable Media', status: 'missed' },
    ],
  },
  {
    tactic: 'Execution',
    id: 'TA0002',
    techniques: [
      { id: 'T1059', name: 'Command Interpreter', status: 'detected' },
      { id: 'T1053', name: 'Scheduled Task', status: 'partial' },
      { id: 'T1204', name: 'User Execution', status: 'detected' },
      { id: 'T1047', name: 'WMI', status: 'partial' },
      { id: 'T1106', name: 'Native API', status: 'none' },
    ],
  },
  {
    tactic: 'Persistence',
    id: 'TA0003',
    techniques: [
      { id: 'T1547', name: 'Boot Autostart', status: 'detected' },
      { id: 'T1543', name: 'Create/Modify Service', status: 'partial' },
      { id: 'T1136', name: 'Create Account', status: 'detected' },
      { id: 'T1078', name: 'Valid Accounts', status: 'partial' },
      { id: 'T1505', name: 'Server Software', status: 'none' },
    ],
  },
  {
    tactic: 'Priv. Escalation',
    id: 'TA0004',
    techniques: [
      { id: 'T1548', name: 'Abuse Elevation', status: 'partial' },
      { id: 'T1068', name: 'Exploit Vuln', status: 'missed' },
      { id: 'T1055', name: 'Process Injection', status: 'partial' },
      { id: 'T1134', name: 'Access Token Manip', status: 'none' },
      { id: 'T1484', name: 'Domain Policy Mod', status: 'none' },
    ],
  },
  {
    tactic: 'Defense Evasion',
    id: 'TA0005',
    techniques: [
      { id: 'T1070', name: 'Indicator Removal', status: 'partial' },
      { id: 'T1036', name: 'Masquerading', status: 'detected' },
      { id: 'T1055', name: 'Process Injection', status: 'partial' },
      { id: 'T1562', name: 'Impair Defenses', status: 'missed' },
      { id: 'T1027', name: 'Obfuscated Files', status: 'partial' },
    ],
  },
  {
    tactic: 'Credential Access',
    id: 'TA0006',
    techniques: [
      { id: 'T1110', name: 'Brute Force', status: 'detected' },
      { id: 'T1003', name: 'OS Credentials', status: 'partial' },
      { id: 'T1558', name: 'Steal Kerberos', status: 'none' },
      { id: 'T1552', name: 'Unsecured Creds', status: 'partial' },
      { id: 'T1555', name: 'Creds from Stores', status: 'none' },
    ],
  },
  {
    tactic: 'Lateral Movement',
    id: 'TA0008',
    techniques: [
      { id: 'T1021', name: 'Remote Services', status: 'detected' },
      { id: 'T1570', name: 'Lateral Tool Trans.', status: 'partial' },
      { id: 'T1534', name: 'Internal Spearphish', status: 'none' },
      { id: 'T1557', name: 'MITM', status: 'none' },
      { id: 'T1550', name: 'Use Alt Auth Mat.', status: 'partial' },
    ],
  },
  {
    tactic: 'Command & Control',
    id: 'TA0011',
    techniques: [
      { id: 'T1071', name: 'App Layer Protocol', status: 'detected' },
      { id: 'T1095', name: 'Non-App Layer Prot.', status: 'partial' },
      { id: 'T1572', name: 'Protocol Tunneling', status: 'none' },
      { id: 'T1090', name: 'Proxy', status: 'none' },
      { id: 'T1102', name: 'Web Service', status: 'partial' },
    ],
  },
  {
    tactic: 'Exfiltration',
    id: 'TA0010',
    techniques: [
      { id: 'T1041', name: 'Exfil Over C2', status: 'partial' },
      { id: 'T1048', name: 'Exfil Alt Protocol', status: 'none' },
      { id: 'T1567', name: 'Exfil to Web Svc', status: 'none' },
      { id: 'T1029', name: 'Scheduled Transfer', status: 'none' },
      { id: 'T1030', name: 'Data Size Limits', status: 'none' },
    ],
  },
]
