"""
Excel export of the shift report — the same window/data the AI Shift Summary
card shows, as a downloadable .xlsx: Overview, Summary, Alerts, Cases and
Decisions sheets, styled like a real SOC handover document rather than a
flat data dump.
"""
from __future__ import annotations

import io
from collections import Counter

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.worksheet.worksheet import Worksheet

from . import shift_summary
from .models import Alert, Case, DecisionRecord

_MIN_COL_WIDTH = 12
_MAX_COL_WIDTH = 60

_HEADER_FILL = PatternFill("solid", fgColor="1F2937")
_HEADER_FONT = Font(bold=True, color="FFFFFF")
_TITLE_FONT = Font(bold=True, size=16, color="1F2937")
_SUBTITLE_FONT = Font(size=10, color="6B7280")
_SECTION_FONT = Font(bold=True, size=11, color="1F2937")
_FOOTER_FONT = Font(italic=True, size=8, color="9CA3AF")

# Severity -> (fill, font color), used for the Risk Score cell in Alerts.
_SEVERITY_FILL = {
    "Critical": PatternFill("solid", fgColor="F8696B"),
    "High": PatternFill("solid", fgColor="FFB570"),
    "Medium": PatternFill("solid", fgColor="FFEB84"),
    "Low": PatternFill("solid", fgColor="A9D08E"),
    "Informational": PatternFill("solid", fgColor="D9D9D9"),
}
_SEVERITY_FONT = {
    "Critical": Font(bold=True, color="9C0006"),
    "High": Font(bold=True, color="9C5700"),
    "Medium": Font(bold=True, color="7F6000"),
    "Low": Font(bold=True, color="375623"),
    "Informational": Font(bold=True, color="404040"),
}

# KPI card fills, in display order.
_KPI_FILLS = ["1F2937", "F8696B", "FFB570", "0EA5E9", "22C55E"]


def _style_header_row(ws: Worksheet, row: int, n_cols: int) -> None:
    for col in range(1, n_cols + 1):
        cell = ws.cell(row=row, column=col)
        cell.fill = _HEADER_FILL
        cell.font = _HEADER_FONT


def _autosize(ws: Worksheet, headers: list[str], rows: list[list]) -> None:
    for col_idx, header in enumerate(headers, start=1):
        letter = ws.cell(row=1, column=col_idx).column_letter
        widest = len(str(header))
        for row in rows:
            value = row[col_idx - 1]
            widest = max(widest, len(str(value)) if value is not None else 0)
        ws.column_dimensions[letter].width = max(_MIN_COL_WIDTH, min(widest + 2, _MAX_COL_WIDTH))


def _footer(ws: Worksheet, row: int, n_cols: int) -> None:
    ws.cell(row=row, column=1, value="Generated by SOCore SOC Platform · Confidential").font = _FOOTER_FONT
    if n_cols > 1:
        ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=n_cols)


def _write_table(ws: Worksheet, headers: list[str], rows: list[list], header_row: int = 1) -> int:
    """Writes a header + data rows starting at `header_row`. Returns the row
    index right after the last data row (or header, if there were none)."""
    for col, header in enumerate(headers, start=1):
        ws.cell(row=header_row, column=col, value=header)
    _style_header_row(ws, header_row, len(headers))
    for r, row in enumerate(rows, start=header_row + 1):
        for c, value in enumerate(row, start=1):
            ws.cell(row=r, column=c, value=value)
    _autosize(ws, headers, rows)
    return header_row + len(rows) + 1


def _misp_match(alert: Alert) -> str:
    return "Yes" if any(s.name == "MISP" and s.status.value == "hit" for s in alert.sources) else "No"


def _proposed_action(alert: Alert) -> str:
    if not alert.proposedAction:
        return "—"
    return f"{alert.proposedAction.action} → {alert.proposedAction.target}"


def _build_overview(
    ws: Worksheet,
    hours: int,
    generated_at: str,
    windowed: list[Alert],
    opened_cases: list[Case],
    windowed_decisions: list[DecisionRecord],
) -> None:
    ws["A1"] = "SOCore — Shift Report"
    ws["A1"].font = _TITLE_FONT
    ws["A2"] = f"Generated {generated_at} · Window: last {hours} hours"
    ws["A2"].font = _SUBTITLE_FONT

    critical_count = sum(1 for a in windowed if a.severity.value == "Critical")
    avg_risk = round(sum(a.riskScore for a in windowed) / len(windowed), 1) if windowed else 0

    kpis = [
        ("Total Alerts", len(windowed)),
        ("Critical Count", critical_count),
        ("Avg Risk Score", avg_risk),
        ("Cases Opened", len(opened_cases)),
        ("Decisions Made", len(windowed_decisions)),
    ]

    # 5 KPI cards, 2 columns wide each, starting at row 4.
    label_row, value_row = 4, 5
    for i, (label, value) in enumerate(kpis):
        start_col = 1 + i * 2
        end_col = start_col + 1
        fill = PatternFill("solid", fgColor=_KPI_FILLS[i % len(_KPI_FILLS)])

        ws.merge_cells(start_row=label_row, start_column=start_col, end_row=label_row, end_column=end_col)
        label_cell = ws.cell(row=label_row, column=start_col, value=label)
        label_cell.font = Font(bold=True, color="FFFFFF", size=9)
        label_cell.fill = fill
        label_cell.alignment = Alignment(horizontal="center")

        ws.merge_cells(start_row=value_row, start_column=start_col, end_row=value_row + 1, end_column=end_col)
        value_cell = ws.cell(row=value_row, column=start_col, value=value)
        value_cell.font = Font(bold=True, color="FFFFFF", size=18)
        value_cell.fill = fill
        value_cell.alignment = Alignment(horizontal="center", vertical="center")

        for col in (start_col, end_col):
            ws.column_dimensions[ws.cell(row=1, column=col).column_letter].width = _MIN_COL_WIDTH

    # ── Top attack types ─────────────────────────────────────────────────
    attack_counts = Counter(a.attackType for a in windowed).most_common(8)
    ws["A8"] = "Top Attack Types"
    ws["A8"].font = _SECTION_FONT
    next_row = _write_table(ws, ["Attack Type", "Count"], [[t, c] for t, c in attack_counts], header_row=9)

    # ── Top source countries ─────────────────────────────────────────────
    country_counts = Counter(a.country for a in windowed if a.country and a.country != "INTERNAL").most_common(8)
    countries_start = next_row + 2
    ws.cell(row=countries_start - 1, column=1, value="Top Source Countries").font = _SECTION_FONT
    footer_row = _write_table(
        ws, ["Country", "Count"], [[c, n] for c, n in country_counts], header_row=countries_start
    )

    _footer(ws, footer_row + 1, 10)


def build_workbook(
    alerts: list[Alert],
    cases: list[Case],
    decisions: list[DecisionRecord],
    hours: int,
    summary_text: str,
    generated_at: str,
) -> bytes:
    windowed = shift_summary.windowed_alerts(alerts, hours)
    opened_cases = shift_summary.windowed_cases(cases, hours)
    windowed_ids = {a.id for a in windowed}
    windowed_decisions = [d for d in decisions if d.alertId in windowed_ids]

    critical_count = sum(1 for a in windowed if a.severity.value == "Critical")
    avg_risk = round(sum(a.riskScore for a in windowed) / len(windowed), 1) if windowed else 0

    wb = Workbook()

    # ── Overview (first sheet) ──────────────────────────────────────────
    ws_overview = wb.active
    ws_overview.title = "Overview"
    _build_overview(ws_overview, hours, generated_at, windowed, opened_cases, windowed_decisions)

    # ── Summary ──────────────────────────────────────────────────────────
    ws = wb.create_sheet("Summary")
    ws["A1"] = "SOCore Shift Report"
    ws["A1"].font = Font(bold=True, size=14)
    ws["A2"] = f"Window: last {hours} hours"
    ws["A3"] = f"Generated: {generated_at}"
    ws["A5"] = "AI Shift Summary"
    ws["A5"].font = _SECTION_FONT
    ws["A6"] = summary_text
    ws["A6"].alignment = Alignment(wrap_text=True, vertical="top")
    ws.merge_cells("A6:F10")
    ws.column_dimensions["A"].width = 100

    stats_row = 12
    ws.cell(row=stats_row, column=1, value="Metric")
    ws.cell(row=stats_row, column=2, value="Value")
    _style_header_row(ws, stats_row, 2)
    stats = [
        ("Total alerts in window", len(windowed)),
        ("Critical alerts", critical_count),
        ("Average risk score", avg_risk),
        ("Cases opened in window", len(opened_cases)),
        ("Decisions logged in window", len(windowed_decisions)),
    ]
    for i, (label, value) in enumerate(stats, start=stats_row + 1):
        ws.cell(row=i, column=1, value=label)
        ws.cell(row=i, column=2, value=value)
    ws.column_dimensions["B"].width = 14
    _footer(ws, stats_row + len(stats) + 2, 6)

    # ── Alerts ───────────────────────────────────────────────────────────
    ws_alerts = wb.create_sheet("Alerts")
    alert_headers = [
        "ID", "Timestamp", "Severity", "Source IP", "Attack Type",
        "MITRE ID", "MITRE Technique", "Country", "ASN",
        "VirusTotal Score", "AbuseIPDB Score", "MISP Match",
        "Risk Score", "Status", "Approval Status", "Proposed Action", "Analyst",
    ]
    alert_rows = [
        [
            a.id, a.timestamp, a.severity.value, a.sourceIP, a.attackType,
            a.mitreId, a.mitreName, a.country or "—", a.asn or "—",
            a.vtScore, a.abuseScore, _misp_match(a),
            a.riskScore, a.status.value, a.approvalStatus.value, _proposed_action(a), a.analyst,
        ]
        for a in windowed
    ]
    next_row = _write_table(ws_alerts, alert_headers, alert_rows)
    risk_col = alert_headers.index("Risk Score") + 1
    for r, a in enumerate(windowed, start=2):
        cell = ws_alerts.cell(row=r, column=risk_col)
        fill = _SEVERITY_FILL.get(a.severity.value)
        font = _SEVERITY_FONT.get(a.severity.value)
        if fill:
            cell.fill = fill
        if font:
            cell.font = font
        cell.alignment = Alignment(horizontal="center")
    _footer(ws_alerts, next_row + 1, len(alert_headers))

    # ── Cases ────────────────────────────────────────────────────────────
    ws_cases = wb.create_sheet("Cases")
    next_row = _write_table(
        ws_cases,
        ["ID", "Title", "Status", "Assigned To", "Created"],
        [[c.id, c.title, c.status.value, c.assignedTo, c.createdAt] for c in opened_cases],
    )
    _footer(ws_cases, next_row + 1, 5)

    # ── Decisions ────────────────────────────────────────────────────────
    ws_decisions = wb.create_sheet("Decisions")
    next_row = _write_table(
        ws_decisions,
        ["Alert ID", "Decision", "By", "At", "Reason"],
        [[d.alertId, d.status, d.by, d.at, d.reason] for d in windowed_decisions],
    )
    _footer(ws_decisions, next_row + 1, 5)

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()
